name: flutter_html
description: A Flutter widget rendering static HTML and CSS as Flutter widgets Forked from Sub6Resources
version: 2.2.2
homepage: https://github.com/coindcx-app/flutter_html

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  # Plugin for parsing html
  html: ^0.15.4

  # Plugins for parsing css
  csslib: ^1.0.0

  # Plugins for rendering the <table> tag.
  flutter_layout_grid: ^2.0.7

  # Plugins for rendering the <video> tag.
  video_player: ^2.9.2
  chewie: ^1.8.5

  # Plugin for rendering the <iframe> tag.
  webview_flutter: ^4.9.0

  # Plugins for rendering the <audio> tag.
  chewie_audio: ^1.5.0

  # plugin for firstWhereOrNull extension on lists
  collection: ^1.18.0

  # plugin to convert integers to numerals
  numerus: ^2.2.0

  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
